package sa.med.imc.myimc.Wellness;

public enum GoogleFitActions {
    RAW_STEPS_COUNT,
    RECORD_RAW_STEPS_COUNT,
    READ_STEPS_COUNT,
    READ_DISTANCE,
    READ_CALORIES,
    READ_MOVE_MINUTES,
    READ_HEIGHT,
    READ_WEIGHT,
    READ_HEART_RATE,
    READ_BLOOD_PRESSURE,
    READ_BLOOD_GLUCOSE_LEVEL,
    READ_OXYGEN_SATURATION,
    READ_BODY_TEMPERATURE,
    READ_SLEEP_SEGMENT
}
